/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lib from "./lib";
export type { lib };
export type { FastAccess } from "./FastAccess";
export type { FastHistory } from "./FastHistory";
export type { FastRegistry } from "./FastRegistry";
export type { FastToken } from "./FastToken";
export type { Spc } from "./Spc";
