/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IFastAccessInterface extends utils.Interface {
  functions: {
    "addGovernor(address)": FunctionFragment;
    "addMember(address)": FunctionFragment;
    "isGovernor(address)": FunctionFragment;
    "isMember(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addGovernor"
      | "addMember"
      | "isGovernor"
      | "isMember"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addGovernor", values: [string]): string;
  encodeFunctionData(functionFragment: "addMember", values: [string]): string;
  encodeFunctionData(functionFragment: "isGovernor", values: [string]): string;
  encodeFunctionData(functionFragment: "isMember", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "addGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isGovernor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;

  events: {};
}

export interface IFastAccess extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFastAccessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addGovernor(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addMember(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isGovernor(c: string, overrides?: CallOverrides): Promise<[boolean]>;

    isMember(c: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  addGovernor(
    c: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addMember(
    c: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isGovernor(c: string, overrides?: CallOverrides): Promise<boolean>;

  isMember(c: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    addGovernor(c: string, overrides?: CallOverrides): Promise<void>;

    addMember(c: string, overrides?: CallOverrides): Promise<void>;

    isGovernor(c: string, overrides?: CallOverrides): Promise<boolean>;

    isMember(c: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addGovernor(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addMember(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isGovernor(c: string, overrides?: CallOverrides): Promise<BigNumber>;

    isMember(c: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addGovernor(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addMember(
      c: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isGovernor(
      c: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMember(
      c: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
