/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IFastHistoryInterface extends utils.Interface {
  functions: {
    "addMintingProof(uint256,string)": FunctionFragment;
    "addTransferProof(address,address,address,uint256,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addMintingProof" | "addTransferProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addMintingProof",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addTransferProof",
    values: [string, string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMintingProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTransferProof",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFastHistory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFastHistoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMintingProof(
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addTransferProof(
      spender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addMintingProof(
    amount: BigNumberish,
    ref: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addTransferProof(
    spender: string,
    from: string,
    to: string,
    amount: BigNumberish,
    ref: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addMintingProof(
      amount: BigNumberish,
      ref: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addTransferProof(
      spender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      ref: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addMintingProof(
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addTransferProof(
      spender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMintingProof(
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addTransferProof(
      spender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      ref: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
