/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1404 } from "./IERC1404";
export type { IERC20 } from "./IERC20";
export type { IFastAccess } from "./IFastAccess";
export type { IFastHistory } from "./IFastHistory";
export type { IFastRegistry } from "./IFastRegistry";
export type { IFastToken } from "./IFastToken";
export type { ISpc } from "./ISpc";
