/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFastHistory,
  IFastHistoryInterface,
} from "../../../contracts/interfaces/IFastHistory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ref",
        type: "string",
      },
    ],
    name: "addMintingProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ref",
        type: "string",
      },
    ],
    name: "addTransferProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFastHistory__factory {
  static readonly abi = _abi;
  static createInterface(): IFastHistoryInterface {
    return new utils.Interface(_abi) as IFastHistoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFastHistory {
    return new Contract(address, _abi, signerOrProvider) as IFastHistory;
  }
}
