/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFastAccess,
  IFastAccessInterface,
} from "../../../contracts/interfaces/IFastAccess";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "c",
        type: "address",
      },
    ],
    name: "addGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "c",
        type: "address",
      },
    ],
    name: "addMember",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "c",
        type: "address",
      },
    ],
    name: "isGovernor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "c",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFastAccess__factory {
  static readonly abi = _abi;
  static createInterface(): IFastAccessInterface {
    return new utils.Interface(_abi) as IFastAccessInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFastAccess {
    return new Contract(address, _abi, signerOrProvider) as IFastAccess;
  }
}
