/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1404__factory } from "./IERC1404__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IFastAccess__factory } from "./IFastAccess__factory";
export { IFastHistory__factory } from "./IFastHistory__factory";
export { IFastRegistry__factory } from "./IFastRegistry__factory";
export { IFastToken__factory } from "./IFastToken__factory";
export { ISpc__factory } from "./ISpc__factory";
