/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISpc, ISpcInterface } from "../../../contracts/interfaces/ISpc";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "c",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISpc__factory {
  static readonly abi = _abi;
  static createInterface(): ISpcInterface {
    return new utils.Interface(_abi) as ISpcInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISpc {
    return new Contract(address, _abi, signerOrProvider) as ISpc;
  }
}
