name: Unit Tests

# Triggers the workflow on all pushes.
on: push

jobs:
  # Main test job.
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install deps
      run: |
        . ./.env
        yarn

    - name: Test coverage
      run: |
        . ./.env
        yarn coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ./coverage.json
        verbose: true
